filepath: ""
namespace: jx-staging
repositories:
- name: dev
  url: http://chartmuseum-jx.3.10.77.173.nip.io
releases:
- chart: dev/election-web-app
  version: 0.0.2
  name: election-web-app
templates: {}
renderedvalues: {}
