filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: http://chartmuseum-jx.35.178.110.181.nip.io
releases:
- chart: dev/election-web-app
  version: 0.0.247
  name: election-web-app
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
