apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: surreyfyp
    provider: github
    repository: election-web-app
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: surreyfyp-election-web-app
  namespace: jx
spec:
  httpCloneURL: https://github.com/surreyfyp/election-web-app.git
  org: surreyfyp
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: election-web-app
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/surreyfyp/election-web-app
