# Source: election-web-app/templates/sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: election-web-app-election-web-app
  annotations:
    meta.helm.sh/release-name: 'election-web-app'
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
